version: '3'
services:
    nginx:
        container_name: laravel_nginx
        image: nginx:latest
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        container_name: laravel_php
        image: php:7.4-fpm
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html

    mysql:
        container_name: laravel_mysql
        image: mysql:latest
        build: ./mysql
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql

    phpmyadmin:
        container_name: laravel_phpmyadmin
        image: phpmyadmin:latest
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOSTS: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        volumes:
            - ./phpmyadmin/sessions:/sessions